source 'https://github.com/Mapxus/mapxusSpecs.git'
source 'https://cdn.cocoapods.org/'

ENV['RCT_NEW_ARCH_ENABLED'] ||= '1'

# Resolve react_native_pods.rb
rn_path = `node -p "require.resolve('react-native/scripts/react_native_pods.rb', {paths: ['#{__dir__}']})"`.strip
require rn_path

platform :ios, '17.4' # Explicit version is safer for New Arch
prepare_react_native_project!

target 'MapxusHsitpExample' do
  use_frameworks! :linkage => :static
  # use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Local development pod
  pod 'MapxusHsitp', :path => '../..'

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.4'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      end
    end
  end
end