# Add these at the very top!
source 'https://github.com/Mapxus/mapxusSpecs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'YourProjectName' do
  use_react_native!
  
  # Link your local Nitro module
  pod 'react-native-mapxus-hsitp', :path => '../modules/react-native-mapxus-hsitp'
  pod 'MapxusMapSDK'
  pod 'MapxusComponentKit'
  pod 'MapxusVisualSDK'
  pod 'SDWebImageSwiftUI'
  pod 'Flow'
  pod 'AFNetworking'
  
  use_frameworks! :linkage => :static
end